# macOS Flutter Application Build GitHub Action

name: macOS Build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # This gives permission to create releases

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.7.2
      - run: dart --version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Enable macOS platform
      - name: Enable macOS platform support
        run: flutter config --enable-macos-desktop

      # Build macOS application
      - name: Build macOS application
        run: flutter build macos --release

      # Package macOS app
      - name: Package macOS app
        run: |
          cd build/macos/Build/Products/Release
          zip -r TIRADSCalculator-macos.zip *.app

      # Archive the built application
      - name: Archive macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/*.zip


      # Create GitHub Release when a tag is pushed
      - name: Release macOS app
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/macos/Build/Products/Release/*.zip
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false